module.exports.descriptors = [
    'forest',
    'ancient',
    'petrified',
    'roaring',
    'cascade',
    'tumbling',
    'silent',
    'redwood',
    'bullfrog',
    'maple',
    'misty',
    'elk',
    'grizzy',
    'ocean',
    'sea',
    'sky',
    'dusty',
    'diamond',
    'golden',
    'scary'
]

module.exports.places = [
    'flats',
    'village',
    'pond',
    'ground camp',
    'horse camp',
    'ghost town',
    'camp',
    'dispersed camp',
    'backcountry',
    'river',
    'creek',
    'creekside',
    'bay',
    'spring',
    'bayshore',
    'sands',
    'mule camp',
    'hunting camp',
    'cliffs',
    'hollow'
]