apiVersion: 1

datasources:
  - name:      Prometheus
    type:      prometheus
    uid:       safar-prom
    url:       http://prometheus:9090
    isDefault: true
    editable:  true
    jsonData:
      timeInterval: "15s"

  - name:     Loki
    type:     loki
    uid:      safar-loki
    url:      http://loki:3100
    editable: true
